# Generated by Django 5.0.6 on 2024-05-19 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dough_divider_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupMembers',
        ),
        migrations.DeleteModel(
            name='TransactionStatus',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserAccounts',
        ),
    ]
