# Generated by Django 5.0.6 on 2024-05-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dough_divider_api', '0002_delete_bankaccount_delete_group_delete_groupmembers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='transaction',
            name='leader',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='transaction',
            name='member',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='completed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
