# Generated by Django 5.0.6 on 2024-05-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dough_divider_api', '0003_remove_transaction_description_transaction_card_and_more'),
        ('dough_divider_api', '0003_transaction_card_transaction_leader_and_more'),
    ]

    operations = [
    ]
