# Generated by Django 5.0.6 on 2024-05-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dough_divider_api', '0004_merge_20240519_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
