# Generated by Django 5.0.6 on 2024-05-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dough_divider_api', '0005_remove_transaction_id_transaction_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
