# Generated by Django 5.0.6 on 2024-05-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dough_divider_api', '0006_alter_transaction_transactionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTransaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('leader', models.CharField(default='', max_length=128)),
                ('member', models.CharField(default='', max_length=128)),
                ('amount', models.FloatField()),
                ('note', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
