# Generated by Django 5.0.6 on 2024-05-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dough_divider_api', '0007_completedtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtransaction',
            name='date',
            field=models.CharField(default='', max_length=8),
        ),
    ]
